/**
  *@file my_protocolService.c
  *@brief generated code for my_protocol packet service
  *@author make_protocol.py
  *@date 02/20/20
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/

#include "my_protocolService.h"
#include <assert.h>

//Define Standard packet IDs
#define MP_PACKET_PING_ID 0
#define MP_PACKET_ACK_ID 1

//Define Struct IDs
#define MP_STRUCT_DEVICE_ID 2

//Define packet IDs
#define MP_PACKET_GETDATA_ID 3
#define MP_PACKET_WHOAREYOU_ID 4
#define MP_PACKET_MYNAMEIS_ID 5
#define MP_PACKET_SETNAME_ID 6
#define MP_PACKET_SENSORDATA_ID 7


//Global descriptors
poly_packet_desc_t* MP_PACKET_PING;
poly_packet_desc_t* MP_PACKET_ACK;
poly_packet_desc_t* MP_PACKET_GETDATA;
poly_packet_desc_t* MP_PACKET_WHOAREYOU;
poly_packet_desc_t* MP_PACKET_MYNAMEIS;
poly_packet_desc_t* MP_PACKET_SETNAME;
poly_packet_desc_t* MP_PACKET_SENSORDATA;

poly_packet_desc_t* MP_STRUCT_DEVICE;

poly_field_desc_t* MP_FIELD_ICD;
poly_field_desc_t* MP_FIELD_DEVICENAME;
poly_field_desc_t* MP_FIELD_TEMP;
poly_field_desc_t* MP_FIELD_HUMIDITY;

//Global descriptors
poly_packet_desc_t _MP_PACKET_PING;
poly_packet_desc_t _MP_PACKET_ACK;
poly_packet_desc_t _MP_PACKET_GETDATA;
poly_packet_desc_t _MP_PACKET_WHOAREYOU;
poly_packet_desc_t _MP_PACKET_MYNAMEIS;
poly_packet_desc_t _MP_PACKET_SETNAME;
poly_packet_desc_t _MP_PACKET_SENSORDATA;

poly_packet_desc_t _MP_STRUCT_DEVICE;

poly_field_desc_t _MP_FIELD_ICD;
poly_field_desc_t _MP_FIELD_DEVICENAME;
poly_field_desc_t _MP_FIELD_TEMP;
poly_field_desc_t _MP_FIELD_HUMIDITY;

static poly_service_t MP_SERVICE;

/*******************************************************************************
  Service Functions
*******************************************************************************/

/**
  *@brief initializes mp_protocol
  *@param interfaceCount number of interfaces to create
  */
void mp_service_init(int interfaceCount, int depth)
{
  //initialize core service
  poly_service_init(&MP_SERVICE,8, interfaceCount);

//Build Standard Packet Descriptors
  MP_PACKET_PING = poly_packet_desc_init(&_MP_PACKET_PING ,MP_PACKET_PING_ID,"Ping", 1);
  MP_PACKET_ACK = poly_packet_desc_init(&_MP_PACKET_ACK ,MP_PACKET_ACK_ID,"Ack", 0);

//Build Struct Descriptors
  MP_STRUCT_DEVICE = poly_packet_desc_init(&_MP_STRUCT_DEVICE ,MP_STRUCT_DEVICE_ID,"Device", 3);

//Build Packet Descriptors
  MP_PACKET_GETDATA = poly_packet_desc_init(&_MP_PACKET_GETDATA ,MP_PACKET_GETDATA_ID,"getData", 0);
  MP_PACKET_WHOAREYOU = poly_packet_desc_init(&_MP_PACKET_WHOAREYOU ,MP_PACKET_WHOAREYOU_ID,"whoAreYou", 0);
  MP_PACKET_MYNAMEIS = poly_packet_desc_init(&_MP_PACKET_MYNAMEIS ,MP_PACKET_MYNAMEIS_ID,"myNameIs", 1);
  MP_PACKET_SETNAME = poly_packet_desc_init(&_MP_PACKET_SETNAME ,MP_PACKET_SETNAME_ID,"setName", 1);
  MP_PACKET_SENSORDATA = poly_packet_desc_init(&_MP_PACKET_SENSORDATA ,MP_PACKET_SENSORDATA_ID,"sensorData", 2);

  //Build Field Descriptors
  MP_FIELD_ICD = poly_field_desc_init( &_MP_FIELD_ICD ,"icd", TYPE_UINT32, 1, FORMAT_DEFAULT);
  MP_FIELD_DEVICENAME = poly_field_desc_init( &_MP_FIELD_DEVICENAME ,"deviceName", TYPE_STRING, 32, FORMAT_DEFAULT);
  MP_FIELD_TEMP = poly_field_desc_init( &_MP_FIELD_TEMP ,"temp", TYPE_INT, 1, FORMAT_DEFAULT);
  MP_FIELD_HUMIDITY = poly_field_desc_init( &_MP_FIELD_HUMIDITY ,"humidity", TYPE_INT, 1, FORMAT_DEFAULT);

  //Setting Field Descriptors for packet: Ping
  poly_packet_desc_add_field(MP_PACKET_PING , MP_FIELD_ICD , true );




  //Setting Field Descriptors for packet: myNameIs
  poly_packet_desc_add_field(MP_PACKET_MYNAMEIS , MP_FIELD_DEVICENAME , false );

  //Setting Field Descriptors for packet: setName
  poly_packet_desc_add_field(MP_PACKET_SETNAME , MP_FIELD_DEVICENAME , false );

  //Setting Field Descriptors for packet: sensorData
  poly_packet_desc_add_field(MP_PACKET_SENSORDATA , MP_FIELD_TEMP , false );
  poly_packet_desc_add_field(MP_PACKET_SENSORDATA , MP_FIELD_HUMIDITY , false );


  //Setting Field Descriptors for struct: Device
  poly_packet_desc_add_field(MP_STRUCT_DEVICE , MP_FIELD_TEMP , false );
  poly_packet_desc_add_field(MP_STRUCT_DEVICE , MP_FIELD_HUMIDITY , false );
  poly_packet_desc_add_field(MP_STRUCT_DEVICE , MP_FIELD_DEVICENAME , false );


  //Register standard packet descriptors with the service
  poly_service_register_desc(&MP_SERVICE, MP_PACKET_PING);
  poly_service_register_desc(&MP_SERVICE, MP_PACKET_ACK);

  //Register Struct descriptors with the service
  poly_service_register_desc(&MP_SERVICE, MP_STRUCT_DEVICE);

  //Register packet descriptors with the service
  poly_service_register_desc(&MP_SERVICE, MP_PACKET_GETDATA);
  poly_service_register_desc(&MP_SERVICE, MP_PACKET_WHOAREYOU);
  poly_service_register_desc(&MP_SERVICE, MP_PACKET_MYNAMEIS);
  poly_service_register_desc(&MP_SERVICE, MP_PACKET_SETNAME);
  poly_service_register_desc(&MP_SERVICE, MP_PACKET_SENSORDATA);

  poly_service_start(&MP_SERVICE, depth);

}


void mp_service_teardown()
{
  //deinit Packet Descriptors
  MP_PACKET_PING = poly_packet_desc_deinit(&_MP_PACKET_PING);
  MP_PACKET_ACK = poly_packet_desc_deinit(&_MP_PACKET_ACK);
  MP_PACKET_GETDATA = poly_packet_desc_deinit(&_MP_PACKET_GETDATA);
  MP_PACKET_WHOAREYOU = poly_packet_desc_deinit(&_MP_PACKET_WHOAREYOU);
  MP_PACKET_MYNAMEIS = poly_packet_desc_deinit(&_MP_PACKET_MYNAMEIS);
  MP_PACKET_SETNAME = poly_packet_desc_deinit(&_MP_PACKET_SETNAME);
  MP_PACKET_SENSORDATA = poly_packet_desc_deinit(&_MP_PACKET_SENSORDATA);

  //deinitialize core service
  poly_service_deinit(&MP_SERVICE);

}

HandlerStatus_e mp_service_dispatch(mp_packet_t* packet, mp_packet_t* response)
{

  HandlerStatus_e mp_status;

  //Dispatch packet
  switch(packet->mDesc->mTypeId)
  {
    case MP_PACKET_PING_ID:
      mp_packet_build(response, MP_PACKET_ACK);
      mp_status = mp_Ping_handler(packet, response);
      break;
    case MP_PACKET_ACK_ID:
      mp_status = mp_Ack_handler(packet);
      break;
    case MP_PACKET_GETDATA_ID:
     mp_packet_build(response, MP_PACKET_SENSORDATA);
     mp_status = mp_GetData_handler(packet , response );
      break;
    case MP_PACKET_WHOAREYOU_ID:
     mp_packet_build(response, MP_PACKET_MYNAMEIS);
     mp_status = mp_WhoAreYou_handler(packet , response );
      break;
    case MP_PACKET_MYNAMEIS_ID:
      mp_status = mp_MyNameIs_handler(packet);
      break;
    case MP_PACKET_SETNAME_ID:
      mp_status = mp_SetName_handler(packet);
      break;
    case MP_PACKET_SENSORDATA_ID:
      mp_status = mp_SensorData_handler(packet);
      break;
    default:
      //we should never get here
      assert(false);
      break;
  }

  //If this packet doe not have an explicit response and AutoAck is enabled, create an ack packet
  if(( MP_SERVICE.mAutoAck ) & (!response->mBuilt) && (!(packet->mHeader.mToken & POLY_ACK_FLAG)))
  {
    mp_packet_build(response, MP_PACKET_ACK);
  }


  //If the packet was not handled, throw it to the default handler
  if(mp_status == PACKET_NOT_HANDLED)
  {
    mp_status = mp_default_handler(packet, response);
  }


  return mp_status;
}

/**
  *@brief attempts to process data in buffers and parse out packets
  */
void mp_service_process()
{
  static mp_packet_t packet;
  static mp_packet_t response;

  HandlerStatus_e mp_status = PACKET_NOT_HANDLED;

  //reset states of static packets
  packet.mBuilt = false;
  packet.mSpooled = false;
  response.mSpooled = false;
  response.mBuilt = false;

  if(poly_service_try_parse(&MP_SERVICE, &packet) == PACKET_VALID)
  {
    //if we get here, then the inner packet was built by the parser
    packet.mBuilt = true;

    mp_status = mp_service_dispatch(&packet,&response);

    //If a response has been build and the mp_status was not set to ignore, we send a response on the intrface it came from
    if(( mp_status == PACKET_HANDLED) && (response.mBuilt) && ((packet.mHeader.mToken & POLY_ACK_FLAG)==0))
    {
      //set response token with ack flag
			response.mHeader.mToken = packet.mHeader.mToken | POLY_ACK_FLAG;

      mp_send(packet.mInterface , &response);
    }

    //Clean the packets
    mp_clean(&packet);
    mp_clean(&response);
  }

  //despool any packets ready to go out
  poly_service_despool(&MP_SERVICE);

}


void mp_service_register_bytes_tx( int iface, poly_tx_bytes_callback txBytesCallBack)
{
  poly_service_register_bytes_tx_callback(&MP_SERVICE, iface,txBytesCallBack);
}

void mp_service_register_packet_tx( int iface, poly_tx_packet_callback txPacketCallBack)
{
  poly_service_register_packet_tx_callback(&MP_SERVICE, iface,txPacketCallBack);
}

void mp_service_feed(int iface, uint8_t* data, int len)
{
  poly_service_feed(&MP_SERVICE,iface,data,len);
}

void mp_service_set_retry(int iface, uint16_t retries, uint32_t timeoutMs)
{
  poly_service_set_retry(&MP_SERVICE, iface,  retries,  timeoutMs);
}

HandlerStatus_e mp_handle_json(const char* req, int len, char* resp)
{
  mp_packet_t packet;
  mp_packet_t response;

  //reset states of static packets
  HandlerStatus_e mp_status = PACKET_NOT_HANDLED;
  packet.mBuilt = false;
  packet.mSpooled = false;
  response.mSpooled = false;
  response.mBuilt = false;


  if(poly_service_parse_json(&MP_SERVICE, &packet, req, len) == PACKET_VALID)
  {
    //if we get here, then the inner packet was built by the parser
    packet.mBuilt = true;

    mp_status = mp_service_dispatch(&packet,&response);


    //If a response has been build and the mp_status was not set to ignore, we send a response on the intrface it came from
    if(( mp_status == PACKET_HANDLED) && (response.mBuilt) )
    {
      //set response token with ack flag
			response.mHeader.mToken = packet.mHeader.mToken | POLY_ACK_FLAG;
      poly_packet_print_json(&response, resp, false);
    }

    //Clean the packets
    mp_clean(&packet);
    mp_clean(&response);

  }
  else
  {
    MRT_SPRINTF(resp,"{\"Error\":\"Parsing Error\"}");
  }

  return mp_status;
}


void mp_service_feed_json(int iface, const char* msg, int len)
{
  poly_service_feed_json_msg(&MP_SERVICE,iface,msg,len);
}


void mp_tick(uint32_t ms)
{
  poly_service_tick(&MP_SERVICE, ms);
}

void mp_auto_ack(bool enable)
{
  MP_SERVICE.mAutoAck = enable;
}

void mp_enable_tx(int iface)
{
  MP_SERVICE.mInterfaces[iface].mTxReady = true;
}

void mp_disable_tx(int iface)
{
  MP_SERVICE.mInterfaces[iface].mTxReady = false;
}


/*******************************************************************************
  Meta packet
*******************************************************************************/

/**
  *@brief initializes a new {proto.prefix}_packet_t
  *@param desc ptr to packet descriptor to model packet from
  */
void mp_packet_build(mp_packet_t* packet, poly_packet_desc_t* desc)
{
  //create new allocated packet
  poly_packet_build(packet, desc, true);
  packet->mAckType = ACK_TYPE_NONE;
  packet->mBuilt = true;
  packet->mSpooled = false;
}


/**
  *@brief frees memory allocated for metapacket
  *@param packet ptr to metaPacket
  *
  */
void mp_clean(mp_packet_t* packet)
{
  //If the packet has been spooled, the spool is responsible for it now
  if(packet->mBuilt && (!packet->mSpooled))
  {
    poly_packet_clean(packet);
  }

}

HandlerStatus_e mp_send(int iface, mp_packet_t* packet)
{
  HandlerStatus_e mp_status;

  mp_status = poly_service_spool(&MP_SERVICE, iface, packet);

  if(mp_status == PACKET_SPOOLED)
  {
    packet->mSpooled = true;
  }

  return mp_status;
}


/*******************************************************************************

  Meta-Packet setters

*******************************************************************************/

/**
  *@brief Sets value of icd field
  *@param packet ptr to mp_packet
  *@param val uint32_t to set field to
  */
void mp_setIcd(mp_packet_t* packet, uint32_t val)
{
  poly_packet_set_field(packet, MP_FIELD_ICD, &val);
}

/**
  *@brief Sets value(s) in deviceName field
  *@param packet ptr to mp_packet
  *@param val char* to copy data from
  */
void mp_setDeviceName(mp_packet_t* packet, const char* val)
{
  poly_packet_set_field(packet, MP_FIELD_DEVICENAME, val);
}

/**
  *@brief Sets value of temp field
  *@param packet ptr to mp_packet
  *@param val int to set field to
  */
void mp_setTemp(mp_packet_t* packet, int val)
{
  poly_packet_set_field(packet, MP_FIELD_TEMP, &val);
}

/**
  *@brief Sets value of humidity field
  *@param packet ptr to mp_packet
  *@param val int to set field to
  */
void mp_setHumidity(mp_packet_t* packet, int val)
{
  poly_packet_set_field(packet, MP_FIELD_HUMIDITY, &val);
}


/*******************************************************************************
  Meta-Packet getters
*******************************************************************************/

/**
  *@brief Gets value of icd field
  *@param packet ptr to mp_packet
  *@return uint32_t data from field
  */
uint32_t mp_getIcd(mp_packet_t* packet)
{
  uint32_t val;
  poly_packet_get_field(packet, MP_FIELD_ICD, &val);
  return val;
}

/**
  *@brief Gets value of deviceName field
  *@param packet ptr to mp_packet
  *@return char* of data in field
  */
void mp_getDeviceName(mp_packet_t* packet, char* val)
{
  poly_packet_get_field(packet, MP_FIELD_DEVICENAME, val);
}

/**
  *@brief Gets value of temp field
  *@param packet ptr to mp_packet
  *@return int data from field
  */
int mp_getTemp(mp_packet_t* packet)
{
  int val;
  poly_packet_get_field(packet, MP_FIELD_TEMP, &val);
  return val;
}

/**
  *@brief Gets value of humidity field
  *@param packet ptr to mp_packet
  *@return int data from field
  */
int mp_getHumidity(mp_packet_t* packet)
{
  int val;
  poly_packet_get_field(packet, MP_FIELD_HUMIDITY, &val);
  return val;
}


/*******************************************************************************
  Quick send functions
*******************************************************************************/

HandlerStatus_e mp_sendPing(int iface)
{
  HandlerStatus_e mp_status;
  //create packet
  mp_packet_t packet;
  mp_packet_build(&packet, MP_PACKET_PING);
  mp_setIcd(&packet,  MP_SERVICE_HASH );

  mp_status = mp_send(iface,&packet); //send packet
  mp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return mp_status;
}

/**
  *@brief sends getData packet
  *@param iface indec of interface to send packet to
  *@return mp_status send attempt
  */
HandlerStatus_e mp_sendGetData(int iface)
{
  HandlerStatus_e mp_status;
  //create packet
  mp_packet_t packet;
  mp_packet_build(&packet,MP_PACKET_GETDATA);

  //set fields

  mp_status = mp_send(iface,&packet); //send packet
  mp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return mp_status;
}
/**
  *@brief sends whoAreYou packet
  *@param iface indec of interface to send packet to
  *@return mp_status send attempt
  */
HandlerStatus_e mp_sendWhoAreYou(int iface)
{
  HandlerStatus_e mp_status;
  //create packet
  mp_packet_t packet;
  mp_packet_build(&packet,MP_PACKET_WHOAREYOU);

  //set fields

  mp_status = mp_send(iface,&packet); //send packet
  mp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return mp_status;
}
/**
  *@brief sends myNameIs packet
  *@param iface indec of interface to send packet to
  *@return mp_status send attempt
  */
HandlerStatus_e mp_sendMyNameIs(int iface)
{
  HandlerStatus_e mp_status;
  //create packet
  mp_packet_t packet;
  mp_packet_build(&packet,MP_PACKET_MYNAMEIS);

  //set fields

  mp_status = mp_send(iface,&packet); //send packet
  mp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return mp_status;
}
/**
  *@brief sends setName packet
  *@param iface indec of interface to send packet to
  *@return mp_status send attempt
  */
HandlerStatus_e mp_sendSetName(int iface)
{
  HandlerStatus_e mp_status;
  //create packet
  mp_packet_t packet;
  mp_packet_build(&packet,MP_PACKET_SETNAME);

  //set fields

  mp_status = mp_send(iface,&packet); //send packet
  mp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return mp_status;
}
/**
  *@brief sends sensorData packet
  *@param iface indec of interface to send packet to
  *@return mp_status send attempt
  */
HandlerStatus_e mp_sendSensorData(int iface)
{
  HandlerStatus_e mp_status;
  //create packet
  mp_packet_t packet;
  mp_packet_build(&packet,MP_PACKET_SENSORDATA);

  //set fields

  mp_status = mp_send(iface,&packet); //send packet
  mp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return mp_status;
}


/*******************************************************************************
  Weak packet handlers

  Do not modify these, just create your own without the '__weak' attribute
*******************************************************************************/
/**
  *@brief Handler for receiving ping packets
  *@param mp_ping ptr to incoming ping packet
  *@param mp_ack ptr to repsonding ack
  *@return PACKET_HANDLED
  */
__attribute__((weak)) HandlerStatus_e mp_Ping_handler(mp_packet_t* mp_ping, mp_packet_t* mp_ack)
{
  /* Ack token has already been set as ping token with POLY_ACK_FLAG*/
  uint32_t icd_hash = mp_getIcd(mp_ping);
  assert(icd_hash == MP_SERVICE_HASH );

  return PACKET_HANDLED;
}

/**
  *@brief Handler for receiving ack packets
  *@param mp_ack ptr to ack
  *@return PACKET_HANDLED
  */
__attribute__((weak)) HandlerStatus_e mp_Ack_handler(mp_packet_t* mp_ack)
{
  return PACKET_HANDLED;
}

/**
  *@brief Handler for receiving getData packets
  *@param getData incoming getData packet
  *@param sensorData sensorData packet to respond with
  *@return handling mp_status
  */
__attribute__((weak)) HandlerStatus_e mp_GetData_handler(mp_packet_t* mp_getData, mp_packet_t* mp_sensorData)
{
  /*  Get Required Fields in packet */

  /*    Set required Fields in response  */
  //mp_setTemp(mp_sensorData, value );  //Temperature in 100ths of a degree. i.e. 4500 = 45.00 deg C
  //mp_setHumidity(mp_sensorData, value );  //Humidity in 100ths of a %. i.e. 5650 = 56.5%Rh


  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}

/**
  *@brief Handler for receiving whoAreYou packets
  *@param whoAreYou incoming whoAreYou packet
  *@param myNameIs myNameIs packet to respond with
  *@return handling mp_status
  */
__attribute__((weak)) HandlerStatus_e mp_WhoAreYou_handler(mp_packet_t* mp_whoAreYou, mp_packet_t* mp_myNameIs)
{
  /*  Get Required Fields in packet */

  /*    Set required Fields in response  */
  //mp_setDeviceName(mp_myNameIs, value );  //Name of device


  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}

/**
  *@brief Handler for receiving myNameIs packets
  *@param myNameIs incoming myNameIs packet
  *@return handling mp_status
  */
__attribute__((weak)) HandlerStatus_e mp_MyNameIs_handler(mp_packet_t* mp_myNameIs)
{
  /*  Get Required Fields in packet */



  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}

/**
  *@brief Handler for receiving setName packets
  *@param setName incoming setName packet
  *@return handling mp_status
  */
__attribute__((weak)) HandlerStatus_e mp_SetName_handler(mp_packet_t* mp_setName)
{
  /*  Get Required Fields in packet */



  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}

/**
  *@brief Handler for receiving sensorData packets
  *@param sensorData incoming sensorData packet
  *@return handling mp_status
  */
__attribute__((weak)) HandlerStatus_e mp_SensorData_handler(mp_packet_t* mp_sensorData)
{
  /*  Get Required Fields in packet */



  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}



/**
  *@brief catch-all handler for any packet not yet handled
  *@param mp_packet ptr to incoming message
  *@param mp_response ptr to response
  *@return handling mp_status
  */
__attribute__((weak)) HandlerStatus_e mp_default_handler( mp_packet_t * mp_packet, mp_packet_t* mp_response)
{

  /* NOTE : This function should not be modified, when the callback is needed,
          mp_default_handler  should be implemented in the user file
  */

  return PACKET_NOT_HANDLED;
}