/**
  * @file hts221_dev.h
  * @author generated by mrt-device utility 
  * @link [https://github.com/uprev-mrt/mrtutils/wiki/mrt-device]
  * @brief values and constants for the HTS221 device registers
  * 
  */

#define HTS221_I2C_ADDRESS 0xBE
#define HTS221_REG_ADDR_SIZE 1


/*******************************************************************************
  Register Addresses                                                                              
*******************************************************************************/

#define HTS_REG_WHO_AM_I_ADDR                                      0x0F /* Id Register */
#define HTS_REG_AV_CONF_ADDR                                       0x10 /* Humidity and temperature resolution mode */
#define HTS_REG_CTRL1_ADDR                                         0x20 /* Control register 1 */
#define HTS_REG_CTRL2_ADDR                                         0x21 /* Control register 2 */
#define HTS_REG_CTRL3_ADDR                                         0x22 /* Control register 3 */
#define HTS_REG_STATUS_ADDR                                        0x27 /* Status register */
#define HTS_REG_HUMIDITY_OUT_ADDR                                  0x28 /* Relative humidity data */
#define HTS_REG_TEMP_OUT_ADDR                                      0x2A /* Temperature data */
#define HTS_REG_H0_RH_X2_ADDR                                      0x30 /* Calibration data */
#define HTS_REG_H1_RH_X2_ADDR                                      0x31 /* Calibration data */
#define HTS_REG_T0_DEGC_X8_ADDR                                    0x32 /* Calibration data */
#define HTS_REG_T1_DEGC_X8_ADDR                                    0x33 /* Calibration data */
#define HTS_REG_T1T0_MSB_ADDR                                      0x35 /* Calibration data */
#define HTS_REG_H0_T0_OUT_ADDR                                     0x36 /* Calibration data */
#define HTS_REG_H1_T0_OUT_ADDR                                     0x3A /* Calibration data */
#define HTS_REG_T0_OUT_ADDR                                        0x3C /* Calibration data */
#define HTS_REG_T1_OUT_ADDR                                        0x3E /* Calibration data */


/*******************************************************************************
  Fields                                                                              
*******************************************************************************/

/* AV_CONF Register Fields */
    /* AV_CONF -> AVGH */
    #define HTS_AV_CONF_AVGH_FIELD_MASK                            0x07 /* Selects the number of Humidity samples to average for data output */
    #define HTS_AV_CONF_AVGH_FIELD_OFFSET                          0x00
      #define HTS_AV_CONF_AVGH_4                                   0x00 /* 4 samples */
      #define HTS_AV_CONF_AVGH_8                                   0x01 /* 8 samples */
      #define HTS_AV_CONF_AVGH_16                                  0x02 /* 16 samples */
      #define HTS_AV_CONF_AVGH_32                                  0x03 /* 32 samples */
      #define HTS_AV_CONF_AVGH_64                                  0x04 /* 64 samples */
      #define HTS_AV_CONF_AVGH_128                                 0x05 /* 128 samples */
      #define HTS_AV_CONF_AVGH_256                                 0x06 /* 256 samples */
      #define HTS_AV_CONF_AVGH_512                                 0x07 /* 512 samples */
    /* AV_CONF -> AVGT */
    #define HTS_AV_CONF_AVGT_FIELD_MASK                            0x38 /* Selects the number of Temperature samples to average for data output */
    #define HTS_AV_CONF_AVGT_FIELD_OFFSET                          0x03
      #define HTS_AV_CONF_AVGT_2                                   0x00 /* 2 samples */
      #define HTS_AV_CONF_AVGT_4                                   0x01 /* 4 samples */
      #define HTS_AV_CONF_AVGT_8                                   0x02 /* 8 samples */
      #define HTS_AV_CONF_AVGT_16                                  0x03 /* 16 samples */
      #define HTS_AV_CONF_AVGT_32                                  0x04 /* 32 samples */
      #define HTS_AV_CONF_AVGT_64                                  0x05 /* 64 samples */
      #define HTS_AV_CONF_AVGT_128                                 0x06 /* 128 samples */
      #define HTS_AV_CONF_AVGT_256                                 0x07 /* 256 samples */

/* CTRL1 Register Fields */
    /* CTRL1 -> Flags */
    #define HTS_CTRL1_PD                                           0x80 /* power down mode */
    #define HTS_CTRL1_BDU                                          0x04 /* Block Data update. Prevents update until LSB of data is read */
    /* CTRL1 -> ODR */
    #define HTS_CTRL1_ODR_FIELD_MASK                               0x03 /* Selects the Output rate for the sensor data */
    #define HTS_CTRL1_ODR_FIELD_OFFSET                             0x00
      #define HTS_CTRL1_ODR_ONESHOT                                0x00 /* readings must be requested */
      #define HTS_CTRL1_ODR_1HZ                                    0x01 /* 1 hz sampling */
      #define HTS_CTRL1_ODR_7HZ                                    0x02 /* 7 hz sampling */
      #define HTS_CTRL1_ODR_12_5HZ                                 0x03 /* 12.5 hz sampling */

/* CTRL2 Register Fields */
    /* CTRL2 -> Flags */
    #define HTS_CTRL2_BOOT                                         0x80 /* Reboot memory content */
    #define HTS_CTRL2_HEATER                                       0x02 /* Enable intenal heating element */
    #define HTS_CTRL2_ONESHOT                                      0x01 /* Start conversion for new data */

/* STATUS Register Fields */
    /* STATUS -> Flags */
    #define HTS_STATUS_TEMP_READY                                  0x01 /* indicates that a temperature reading is ready */
    #define HTS_STATUS_HUM_READY                                   0x02 /* indicates that a humidity reading is ready */

/* HUMIDITY_OUT Register Fields */
    /* HUMIDITY_OUT -> HUM_OUT */
    #define HTS_HUMIDITY_OUT_HUM_OUT_FIELD_MASK                    0xFFFF /* Current ADC reading for humidity sensor */
    #define HTS_HUMIDITY_OUT_HUM_OUT_FIELD_OFFSET                  0x0000

/* TEMP_OUT Register Fields */
    /* TEMP_OUT -> TEMP_OUT */
    #define HTS_TEMP_OUT_TEMP_OUT_FIELD_MASK                       0xFFFF /* Current ADC reading for temperature sensor */
    #define HTS_TEMP_OUT_TEMP_OUT_FIELD_OFFSET                     0x0000


/*******************************************************************************
  Default Values                                                                              
*******************************************************************************/

#define HTS_WHO_AM_I_DEFAULT                                       0xBC
#define HTS_AV_CONF_DEFAULT                                        0x1B
#define HTS_CTRL1_DEFAULT                                          0x00
#define HTS_CTRL2_DEFAULT                                          0x00
#define HTS_CTRL3_DEFAULT                                          0x00
#define HTS_STATUS_DEFAULT                                         0x00

/*******************************************************************************
  Flag Set/Clear/Check                                                                             
*******************************************************************************/

/**
  *@brief sets flags on device
  *@param dev ptr to HTS221 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define hts_set_flag(dev, reg, mask) regdev_set_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief clears flags on device
  *@param dev ptr to HTS221 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  */
#define hts_clear_flag(dev, reg, mask) regdev_clear_flags(&(dev)->mRegDev,(reg), (mask))

/**
  *@brief checks flags on device
  *@param dev ptr to HTS221 device
  *@param reg ptr to register definition
  *@param mask mask of flags to set
  *@return true if all flags in mask are set 
  *@return false if any flags in mask are not set
  */
#define hts_check_flag(dev, reg, mask) regdev_check_flags(&(dev)->mRegDev,(reg), (mask))

/*******************************************************************************
  Field Getters                                                                              
*******************************************************************************/

/**
 * @brief reads the AVGH field from the AV_CONF register 
 * @param dev ptr to HTS221 device
 * @return HTS_AV_CONF_AVGH_4 4 samples
 * @return HTS_AV_CONF_AVGH_8 8 samples
 * @return HTS_AV_CONF_AVGH_16 16 samples
 * @return HTS_AV_CONF_AVGH_32 32 samples
 * @return HTS_AV_CONF_AVGH_64 64 samples
 * @return HTS_AV_CONF_AVGH_128 128 samples
 * @return HTS_AV_CONF_AVGH_256 256 samples
 * @return HTS_AV_CONF_AVGH_512 512 samples
 */
#define hts_get_av_conf_avgh(dev) regdev_read_field(&(dev)->mRegDev, &(dev)->mAvConf, HTS_AV_CONF_AVGH_FIELD_MASK )

/**
 * @brief reads the AVGT field from the AV_CONF register 
 * @param dev ptr to HTS221 device
 * @return HTS_AV_CONF_AVGT_2 2 samples
 * @return HTS_AV_CONF_AVGT_4 4 samples
 * @return HTS_AV_CONF_AVGT_8 8 samples
 * @return HTS_AV_CONF_AVGT_16 16 samples
 * @return HTS_AV_CONF_AVGT_32 32 samples
 * @return HTS_AV_CONF_AVGT_64 64 samples
 * @return HTS_AV_CONF_AVGT_128 128 samples
 * @return HTS_AV_CONF_AVGT_256 256 samples
 */
#define hts_get_av_conf_avgt(dev) regdev_read_field(&(dev)->mRegDev, &(dev)->mAvConf, HTS_AV_CONF_AVGT_FIELD_MASK )

/**
 * @brief reads the ODR field from the CTRL1 register 
 * @param dev ptr to HTS221 device
 * @return HTS_CTRL1_ODR_ONESHOT readings must be requested
 * @return HTS_CTRL1_ODR_1HZ 1 hz sampling
 * @return HTS_CTRL1_ODR_7HZ 7 hz sampling
 * @return HTS_CTRL1_ODR_12_5HZ 12.5 hz sampling
 */
#define hts_get_ctrl1_odr(dev) regdev_read_field(&(dev)->mRegDev, &(dev)->mCtrl1, HTS_CTRL1_ODR_FIELD_MASK )

/**
 * @brief reads the HUM_OUT field from the HUMIDITY_OUT register 
 * @param dev ptr to HTS221 device
 */
#define hts_get_humidity_out_hum_out(dev) regdev_read_field(&(dev)->mRegDev, &(dev)->mHumidityOut, HTS_HUMIDITY_OUT_HUM_OUT_FIELD_MASK )

/**
 * @brief reads the TEMP_OUT field from the TEMP_OUT register 
 * @param dev ptr to HTS221 device
 */
#define hts_get_temp_out_temp_out(dev) regdev_read_field(&(dev)->mRegDev, &(dev)->mTempOut, HTS_TEMP_OUT_TEMP_OUT_FIELD_MASK )



/*******************************************************************************
  Field Setters                                                                              
*******************************************************************************/

/**
 * @brief writes the AVGH field to the AV_CONF register 
 * @param dev ptr to HTS221 device
 * @option HTS_AV_CONF_AVGH_4 4 samples
 * @option HTS_AV_CONF_AVGH_8 8 samples
 * @option HTS_AV_CONF_AVGH_16 16 samples
 * @option HTS_AV_CONF_AVGH_32 32 samples
 * @option HTS_AV_CONF_AVGH_64 64 samples
 * @option HTS_AV_CONF_AVGH_128 128 samples
 * @option HTS_AV_CONF_AVGH_256 256 samples
 * @option HTS_AV_CONF_AVGH_512 512 samples
 */
#define hts_set_av_conf_avgh(dev, val) regdev_write_field(&(dev)->mRegDev, &(dev)->mAvConf, HTS_AV_CONF_AVGH_FIELD_MASK , (val) )

/**
 * @brief writes the AVGT field to the AV_CONF register 
 * @param dev ptr to HTS221 device
 * @option HTS_AV_CONF_AVGT_2 2 samples
 * @option HTS_AV_CONF_AVGT_4 4 samples
 * @option HTS_AV_CONF_AVGT_8 8 samples
 * @option HTS_AV_CONF_AVGT_16 16 samples
 * @option HTS_AV_CONF_AVGT_32 32 samples
 * @option HTS_AV_CONF_AVGT_64 64 samples
 * @option HTS_AV_CONF_AVGT_128 128 samples
 * @option HTS_AV_CONF_AVGT_256 256 samples
 */
#define hts_set_av_conf_avgt(dev, val) regdev_write_field(&(dev)->mRegDev, &(dev)->mAvConf, HTS_AV_CONF_AVGT_FIELD_MASK , (val) )

/**
 * @brief writes the ODR field to the CTRL1 register 
 * @param dev ptr to HTS221 device
 * @option HTS_CTRL1_ODR_ONESHOT readings must be requested
 * @option HTS_CTRL1_ODR_1HZ 1 hz sampling
 * @option HTS_CTRL1_ODR_7HZ 7 hz sampling
 * @option HTS_CTRL1_ODR_12_5HZ 12.5 hz sampling
 */
#define hts_set_ctrl1_odr(dev, val) regdev_write_field(&(dev)->mRegDev, &(dev)->mCtrl1, HTS_CTRL1_ODR_FIELD_MASK , (val) )


/*******************************************************************************
  Configs                                                                            
*******************************************************************************/

/**
 * @brief Sets device to update every second
 * @param dev ptr to HTS221 device
 */
#define HTS_LOAD_CONFIG_AUTO_1HZ(dev) \
hts_write_reg( (dev), &(dev)->mCtrl2, 0x80);     /* BOOT: 1 */                    \
MRT_DELAY_MS(10);                                /* Delay for CTRL2 */ \
hts_write_reg( (dev), &(dev)->mCtrl1, 0x01);     /* ODR: 1HZ */                   \

